apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: ricardofood
  name: rabbitmq-cluster
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi  