pipeline {
    agent any
    
    tools {
        maven 'maven3'
        jdk 'jdk17'
    }
    
    environment {
        SCANNER_HOME= tool 'sonar-scanner'
    }
    

    stages {
        stage('Git checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ricardo85x/ricardofood-discovery-server'
            }
        }

        stage('Git checkout devops repository') {
            steps {
                dir('devops') {
                    git branch: 'main', url: 'https://github.com/ricardo85x/ricardofood-devops'
                }
            }
        }
        
        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar') {
                    sh "$SCANNER_HOME/bin/sonar-scanner -Dsonar.projectKey=ricardofood_eureka -Dsonar.projectName=ricardofood_eureka -Dsonar.java.binaries=."
                }
            }
        }
        
        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '', nvdCredentialsId: 'nvd-nist-key', odcInstallation: 'DC'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }
        
        stage('Deploy To Nexus') {
            steps {
                withMaven(globalMavenSettingsConfig: 'global-maven', jdk: 'jdk17', maven: 'maven3', mavenSettingsConfig: '', traceability: true) {
                    sh "mvn deploy"
                }
            }
        }
        
        stage('Build & Tag Docker Image') {
            steps {
                script {
                    def version = sh(script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout", returnStdout: true).trim()

                    echo "Building version: ${version}"

                    sh "mv -f ./target/eureka_server-${version}.jar ./target/eureka_server.jar"

                    sh "docker build -t ricardo85x/ricardofood-eureka:${version} -f docker/Dockerfile ."
                    sh "docker tag ricardo85x/ricardofood-eureka:${version} ricardo85x/ricardofood-eureka:latest"
                    
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh "trivy image ricardo85x/ricardofood-eureka:latest > trivy-report.txt "
                
            }
        }

        stage('Push The Docker Image') {
            steps {
                script {

                    def version = sh(script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout", returnStdout: true).trim()

                    withDockerRegistry(credentialsId: 'docker-hub-cred') {
                        sh "docker push ricardo85x/ricardofood-eureka:${version}"
                        sh "docker push ricardo85x/ricardofood-eureka:latest"
                    }   
                }
                 
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'k8-token', namespace: 'webapps', restrictKubeConfigAccess: false, serverUrl: ' https://172.31.15.138:6443') {
                    sh "kubectl apply -f deploymentservice.yml -n webapps"
                    sh "kubectl get svc -n webapps"
    
                }
            }
        }
        
    }
}
