services:

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "${JENKINS_PORT:-8088}:8080"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      DOCKER_HOST: "${DOCKER_HOST:-tcp://192.168.3.133:2375}"
    volumes:
      - ricardofood_jenkins_home:/var/jenkins_home
    networks:
      - ricardofood_network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "${SONARQUBE_PORT:-9000}:9000"
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL:-jdbc:postgresql://db:5432/sonarqube}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME:-sonar}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD:-sonar}
    depends_on:
      - db
    networks:
      - ricardofood_network

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sonar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sonar}
      POSTGRES_DB: ${POSTGRES_DB:-sonarqube}
    networks:
      - ricardofood_network

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "${NEXUS_PORT:-8081}:8081"
    networks:
      - ricardofood_network

networks:
  ricardofood_network:
    driver: bridge

volumes:
  ricardofood_jenkins_home:
