apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ricardofood
  name: eureka-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: eureka
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka-container
        image: ricardo85x/ricardofood-eureka:latest
        envFrom:
          - configMapRef:
              name: eureka-configmap
        resources:
          requests:
            cpu: 2000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 2Gi
  selector:
    matchLabels:
      app: eureka