apiVersion: v1
kind: Service
metadata:
  namespace: ricardofood
  name: eureka
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP
