apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ricardofood
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-hostpath-sc
