apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: ricardofood
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        envFrom:
          - configMapRef:
              name: mysql-configmap
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc