apiVersion: v1
kind: Service
metadata:
  namespace: ricardofood
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
  clusterIP: None
