apiVersion: v1
kind: Service
metadata:
  namespace: ricardofood
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: http
  type: LoadBalancer
