apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ricardofood
  name: gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: gateway
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: ricardo85x/ricardofood-gateway:latest
        envFrom:
          - configMapRef:
              name: gateway-configmap
        resources:
          requests:
            cpu: 2000m
            memory: 5Gi
          limits:
            cpu: 2000m
            memory: 5Gi
  selector:
    matchLabels:
      app: gateway